[project]
name = "app"
version = "0.1.0"
description = "A app template."
readme = "README.md"
authors = [{ name = "Will Rice", email = "wrice20@gmail.com" }]
requires-python = ">=3.13"
dependencies = [
  "gradio>=6.28.0",
  "mypy>=2.3.1",
  "pre-commit>=4.6.2",
  "pydocstyle>=6.3.0",
  "pytest>=9.1.1",
  "python-dotenv>=1.2.3",
  "ruff>=0.16.8",
]

[build-system]
requires = ["uv_build>=0.12.18"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = ["app"]

[tool.ruff.lint.isort]
known-first-party = ["app"]

[tool.ruff.lint]
select = ["C", "E", "F", "I", "W", "D", "N", "B"]
ignore = ["D107"]
exclude = [".venv"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.mypy]
ignore_missing_imports = true
follow_imports_for_stubs = true
exclude = [".venv"]

[project.scripts]
app = "app.app:main"
